### ISSUE TITLE
Pressure_tendency error

### ISSUE THREAD

**Issue by bebach8** [kpisacic/DHMZ-home-assistant-custom-component#4]
Home assistant 0.115.3

3 errors in new version.

ERROR 1:

Logger: homeassistant.components.weather
Source: custom_components/dhmz/weather.py:260
Integration: Weather (documentation, issues)
First occurred: 5:58:44 PM (1 occurrences)
Last logged: 5:58:44 PM
Error while setting up dhmz platform for weather

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 193, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/dhmz/weather.py", line 124, in setup_platform
    add_entities([DhmzWeather(probe, name)], True)
  File "/config/custom_components/dhmz/weather.py", line 134, in __init__
    self._state = self.format_condition(self.dhmz_data.get_data(SENSOR_TYPES["weather_symbol"][4]))
  File "/config/custom_components/dhmz/weather.py", line 260, in format_condition
    return [
IndexError: list index out of range

ERROR 2:

Logger: homeassistant.components.sensor
Source: custom_components/dhmz/sensor.py:185
Integration: Sensor (documentation, issues)
First occurred: 5:59:06 PM (1 occurrences)
Last logged: 5:59:06 PM
Error while setting up dhmz platform for sensor

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 201, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 310, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 481, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 522, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 296, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 323, in _async_write_ha_state
    attr.update(self.device_state_attributes or {})
  File "/config/custom_components/dhmz/sensor.py", line 185, in device_state_attributes
    ret["pressure_tendency"] = self.probe.get_data(SENSOR_TYPES["pressure_tendency"][4]) + " hPa"
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

Those above causes following ERROR 3:

2020-09-25 18:01:08 ERROR (MainThread) [frontend.js.latest.202009182] https://[redacted]:8123/local/dhmz-weather-card.js:244:45 Uncaught TypeError: Cannot read property 'forecast' of undefined

**Comment by kpisacic** [comment]
This might have been temporary error due to missing attibute in DHMZ output. Is this still happening? I dont see it in my error log.

**Comment by bebach8** [comment]
> 
> 
> This might have been temporary error due to missing attibute in DHMZ output. Is this still happening? I dont see it in my error log.

Da, još uvijek +  još i ovo

Logger: homeassistant.components.weather
Source: custom_components/dhmz/weather.py:208
Integration: Weather (documentation, issues)
First occurred: 7:58:58 AM (2 occurrences)
Last logged: 7:58:58 AM

Error adding entities for domain weather with platform dhmz
Error while setting up dhmz platform for weather
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 315, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 506, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 531, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 296, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 322, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/weather/__init__.py", line 150, in state_attributes
    humidity = self.humidity
  File "/config/custom_components/dhmz/weather.py", line 208, in humidity
    return float(self.dhmz_data.get_data(SENSOR_TYPES[ATTR_WEATHER_HUMIDITY][4]))
ValueError: could not convert string to float: '-'

**Comment by kpisacic** [comment]
These and various other potential value conversion errors handled in dde59174a200d6189ac1b2b26807200a06ec5dc4
